- namespace: experiments.translateUi
  description: Provides browser chrome UI that reacts to translation states and fires events on user interaction

  functions:
    - name: start
      type: function
      async: true
      description: Start reacting to translation state updates
      parameters: [ ]
    - name: setUiState
      type: function
      async: true
      description: Set current ui state
      parameters:
        - name: tabId
          type: number
        - name: uiState
          type: any
    - name: stop
      type: function
      async: true
      description: Stop reacting to translation state updates
      parameters: [ ]

  events:
    - name: onInfoBarDisplayed
      type: function
      description: onInfoBarDisplayed
      parameters: [ ]
    - name: onSelectTranslateTo
      type: function
      description: onSelectTranslateTo
      parameters: [ ]
    - name: onSelectTranslateFrom
      type: function
      description: onSelectTranslateFrom
      parameters: [ ]
    - name: onInfoBarClosed
      type: function
      description: onInfoBarClosed
      parameters: [ ]
    - name: onNeverTranslateSelectedLanguage
      type: function
      description: onNeverTranslateSelectedLanguage
      parameters: [ ]
    - name: onNeverTranslateThisSite
      type: function
      description: onNeverTranslateThisSite
      parameters: [ ]
    - name: onShowOriginalButtonPressed
      type: function
      description: onShowOriginalButtonPressed
      parameters: [ ]
    - name: onShowTranslatedButtonPressed
      type: function
      description: onShowTranslatedButtonPressed
      parameters: [ ]
    - name: onTranslateButtonPressed
      type: function
      description: onTranslateButtonPressed
      parameters: [ ]
    - name: onNotNowButtonPressed
      type: function
      description: onNotNowButtonPressed
      parameters: [ ]
