[book]
title = "Firefox Translations Web Extension - User Guide"
authors = ["Bergamot Team @ Mozilla"]
src = "."

[build]
build-dir = "../../docs/user"
create-missing = true

[output.html]
additional-css = ["../shared/custom.css"]
additional-js = ["../shared/tabs.js", "../shared/mermaid.min.js", "../shared/mermaid-init.js"]
git-repository-url = "https://github.com/mozilla-extensions/firefox-translations"
git-branch = "main"
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"

[preprocessor.mermaid]
command = "mdbook-mermaid"
